TasksApp/TasksApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'TakskApp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^tasks/', include('tasks.urls',namespace="tasks")),

]

TasksApp/tasks/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
               url(r'^(?P<item_id>[0-9]+)/detail/$', views.update_task, name='update_task'),
               url(r'^$',
                   views.add_task, name='add_task'),

               url(r'^todolist/deleteTask/(?P<item_id>\w+)/$',
                   views.deleteTask,name='deleteTask'),

               url(r'^todolist/markIt/(?P<item_id>\w+)/$',
                   views.markIt,name='markIt'),
               ]

TasksApp/tasks/models.py
from django.db import models

class Item(models.Model):

    title = models.CharField(max_length=250)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

TasksApp/tasks/forms.py
from django import forms
from .models import Item

class PostForm(forms.Form):
    Task_Description = forms.CharField(max_length=256,required=False)
    completed = forms.BooleanField(required=False)

class getData(forms.Form):
    Edit_Task_Description = forms.CharField(max_length=256)

TasksApp/tasks/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse

from django.http import HttpResponse
from .models import Item
from .forms import PostForm,getData

def add_task(request):
    """Adds a new task to the list."""
    latest_item_list = Item.objects.order_by('title')
    if request.method == 'GET':
        form = PostForm()
    else:
        form = PostForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['Task_Description']
            completed = form.cleaned_data['completed']
            post = Item.objects.create(title=title,completed=completed)
            return HttpResponseRedirect('/tasks/')

    return render(request, 'tasks/index.html', {'form': form,'latest_item_list': latest_item_list,})

def update_task(request,item_id):
    """Updates an existing task in the list."""
    item = get_object_or_404(Item, pk=item_id)
    form = getData(request.POST)
    if request.method == 'POST':

        if form.is_valid():
            title = form.cleaned_data['Edit_Task_Description']
            updatetask_desc = Item.objects.get(id=item_id)
            updatetask_desc.title = title
            updatetask_desc.save()
            return HttpResponseRedirect(".")
    else:
        form = getData()

    return render(request, 'tasks/detail.html', {'item': item,'form': form,})

def deleteTask(request,item_id):
    """Delete a task in the list."""
    item = Item.objects.get(pk=item_id)
    item.delete()
    return HttpResponseRedirect('/tasks/')

def markIt(request,item_id):
    """Mark a task in the list as completed."""
    item = Item.objects.get(pk=item_id)
    item.completed = True
    item.save()
    return HttpResponseRedirect('/tasks/')

TasksApp/tasks/templates/tasks/detail.html
<!-- This renders the detail page of each task -->

<head>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <style>
            body {
                background-color: linen;

            }

        .btn {
            background: #3498db;
            border-radius: 28px;
            color: #ffffff;

        }

            </style>
</head>

<nav class="navbar navbar-inverse">
    <a href="/tasks/"> <h2> All tasks </h2> </a>
</nav>




<h1>{{item.title}}</h1>

{% if item.completed == False %}
<form action='/tasks/{{item.id}}/detail/' method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" class="btn">
</form>
{% endif %}

TasksApp/tasks/templates/tasks/index.html
<!-- Home page of all the tasks -->

<head>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <style>
            body {
                background-color: linen;

            }

        .btn {
            background: #3498db;
            border-radius: 28px;
            color: #ffffff;

        }

            </style>
</head>

<nav class="navbar navbar-inverse">
    <h1 style="color:white;float: left;padding-left: 35px;">My Tasks! </h1>
</nav>


{% if latest_item_list %}
<ul>
    {% for item in latest_item_list %}
    <li style="list-style-type:none">
        {% if item.completed == True %}
        <a href="/tasks/{{ item.id}}/detail/" style="font-size: 16px;">

            <span id="markdone{{item.id}}"> [x] </span>
            {{ item.title }}</a>
        {% else %}
        <a href="/tasks/{{ item.id}}/detail/" style="font-size: 16px;">

            <span id="markdone{{item.id}}"> [ ] </span>
            {{ item.title }}</a>

        <form action="{%url 'tasks:markIt' item.id %}" method="post" onsubmit="return myFunction({{item.id}})" style="    margin-top: 10px;">
            {% csrf_token %}
            <input type="submit" style="display:block" id="marked{{item.id}}" class="btn" value="Mark Complete">
                </form>
        {% endif %}

        <form action="{%url 'tasks:deleteTask' item.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete" class="btn">
                </form>
    </li>
    {% endfor %}
</ul>
{% else %}
<p style="float: left;padding-left: 35px;font-size: 16px;">No tasks today! :)</p>
{% endif %}

<div style="padding: 35px;">
    <h1>Create a new Task</h1>


    <form action='/tasks/' method='post'>
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Submit" class="btn">
    </form>
</div>
<script>

    function myFunction(id)
    {
        document.getElementById("markdone"+id).innerHTML = "[x]";
        document.getElementById("marked"+id).style.visibility = 'hidden';


    }
</script>